/*
	File: EEGFilter.h
	Created on: 2017.10.9
	Author: Bifei Liu
	Description: This is a class for the filter used in EEG signal, which is based on 
	the Butterworth filter. The filter coefficients are fixed before. And the coefficients 
	can be generated by the function parameterGenerate() in datatest.cpp
		
*/

#pragma once

#include "Biquad.h"
#include <iostream>
#include <fstream>

class EEGFilter
{
public:

	EEGFilter() {
	}
	~EEGFilter() {
	}

	void initCoeffs(int numFilters, double inputCoeffs[][5], double gain);
	void filter(float* input, float *output, int count);


private:

	vector <Biquad> coeffs;
	double overallGain;
	BiquadChain biquadCoeffs;

};